TEMPLATE_FILE_PATH=/home/app/pbc-file/
MAX_HEIGHT_SIZE=280
MAX_WIDTH_SIZE=265
QTR_MAX_HEIGHT_SIZE=400
QTR_MAX_WIDTH_SIZE=550

#每天 16点30执行
cronThreeCertificates=0 30 16 * * ?
#每天 17点30执行
cronEnterprise=0 30 17 * * ?
#接口数据每页多少条
httpPage=1000
