#*********调用预测分析脚本路径***********
ANALYSIS_PYTHON_PATH=/home/shell/sust/grey_prediction.py
#*********下载路径******
DOWNLOAD_PATH=/home/dwb/
#**********系统类型*******
devOps_system=ucloud
network_system=upm
##文件上传配置##
spring.http.multipart.maxFileSize=500Mb
spring.http.multipart.maxRequestSize=1000Mb
#********参数维护的指标预测定时************
forecastSchedule=0 09 14 * * ?
