# Server settings
server:
  port: 8201
  bes:
    basedir: ../document/bes
  store-lic-interval: 0
  session:
    timeout: 30
  context-path: /

spring:
  redis:
    host: 192.168.160.30
    port: 6379
    timeout: 0
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0
  application:
    name: statisticalAnalysis
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/resource/
  # vastbase
  datasource:
    url: jdbc:postgresql://100.71.11.54:25432/gk_data_analysis?currentSchema=dps,public
    username: vastbase_test
    password: "B$S8*^75foTnE*z1"
    driver-class-name: org.postgresql.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    type: com.alibaba.druid.pool.DruidDataSource

cas:
  server-url-prefix: http://192.168.100.74:8443
  server-login-url: ${cas.server-url-prefix}/login
  server-logout-url: ${cas.server-url-prefix}/logout
  client-host-url: http://192.168.100.74:8080
  validation-type: cas
casSecurityEnable: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.160.244:8761/eureka/

mybatis-plus:
  mapper-locations: classpath*:/mybatis/**/*.xml