-- Vastbase source-port bundle for edw core procedures
-- Strategy: keep MySQL B-compatible procedure bodies first, then validate in dependency order.

-- PROCEDURE `edw`.`P_TRS_BUDGET_INCOME_COMPARE`
DROP PROCEDURE IF EXISTS `edw`.`P_TRS_BUDGET_INCOME_COMPARE`;
DELIMITER $$
CREATE DEFINER=`dis`@`%` PROCEDURE `P_TRS_BUDGET_INCOME_COMPARE`(IN P_DATA_DATE VARCHAR(10))
BEGIN
  DECLARE V_PROC_NAME     VARCHAR(80)   DEFAULT 'EDW.P_TRS_BUDGET_INCOME_COMPARE.PRC';
  DECLARE V_START_TIME    CHAR(19)      DEFAULT NOW();
  DECLARE V_STEP_ID       INT           DEFAULT 0;
  DECLARE S_DATA_DATE     VARCHAR(8)	DEFAULT	DATE_FORMAT(P_DATA_DATE,'%Y-%m');
  
  DECLARE done INT DEFAULT 0;
  DECLARE V_DATA_DATE     VARCHAR(8);
  DECLARE cur CURSOR FOR
  SELECT DISTINCT data_date FROM stg.trs_tmis_budget_income_provinces WHERE batch_date = P_DATA_DATE ORDER BY data_date;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
 
     DECLARE EXIT HANDLER FOR SQLEXCEPTION
   BEGIN
       GET DIAGNOSTICS CONDITION 1 @V_RETURN_CODE = RETURNED_SQLSTATE ,@V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(S_DATA_DATE,V_START_TIME,NOW(),TABLE_NAME,V_STEP_ID,@V_RETURN_CODE,@V_ERROR_MSG);
   END; 
  
  
  OPEN cur;
  WHILE
    done <> 1 DO FETCH cur INTO V_DATA_DATE;
    IF done <> 1
    THEN 
select V_DATA_DATE;    
    SET V_STEP_ID = 1;
    
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = V_DATA_DATE;
SET V_STEP_ID = 2;
insert into EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM(101_TATE),4)
	,SUM(101_RANK)
	,ROWS_ID
FROM 
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	@rank:=@rank+1 AS T010101_RANK,
	AA.101_TATE,
	AA.101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN (a.TREDSCR = '新疆兵团' or a.TREDSCR = '新疆区') THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS 101_TATE,
	'' AS 101_RANK,
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
						 WHEN (a.TRECODE = '3100000000' or a.TRECODE = '3000000000')  THEN '3000000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA ,(SELECT @rank:=0) BB
UNION ALL
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA.101_TATE,
	@rank2:=@rank2+1  AS 101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN (a.TREDSCR = '新疆兵团' or a.TREDSCR = '新疆区') THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS 101_TATE,
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
,(SELECT @tate:=NULL,@rank:=0) c
WHERE A.DATA_DATE = V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
						 WHEN (a.TRECODE = '3100000000' or a.TRECODE = '3000000000')  THEN '3000000000'
	     ELSE a.TRECODE
	     END
ORDER BY 101_TATE DESC
) AA ,(SELECT @rank2:=0) BB
) 
)A
GROUP BY 
        PROJECT;
        
 SET V_STEP_ID = 3;       
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = concat(year(concat(V_DATA_DATE,'01')),'Q',quarter(CONCAT(V_DATA_DATE,'01')));
 SET V_STEP_ID = 4;
INSERT INTO EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM(101_TATE),4)
	,SUM(101_RANK)
	,ROWS_ID
FROM 
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	@rank:=@rank+1 AS T010101_RANK,
	AA.101_TATE,
	AA.101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN (a.TREDSCR = '新疆兵团' or a.TREDSCR = '新疆区') THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS 101_TATE,
	'' AS 101_RANK,
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
						 WHEN (a.TRECODE = '3100000000' or a.TRECODE = '3000000000')  THEN '3000000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA ,(SELECT @rank:=0) BB
UNION ALL
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA.101_TATE,
	@rank2:=@rank2+1  AS 101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN (a.TREDSCR = '新疆兵团' or a.TREDSCR = '新疆区') THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS 101_TATE,
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
,(SELECT @tate:=NULL,@rank:=0) c
WHERE a.data_Date =V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
						 WHEN (a.TRECODE = '3100000000' or a.TRECODE = '3000000000')  THEN '3000000000'
	     ELSE a.TRECODE
	     END
ORDER BY 101_TATE DESC
) AA ,(SELECT @rank2:=0) BB
) 
)A
GROUP BY 
        PROJECT;
    END IF;
  END WHILE;
  CLOSE cur;
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_TRS_BUDGET_INCOME_COMPARE_NEW`
DROP PROCEDURE IF EXISTS `edw`.`P_TRS_BUDGET_INCOME_COMPARE_NEW`;
DELIMITER $$
CREATE DEFINER=`dis`@`%` PROCEDURE `P_TRS_BUDGET_INCOME_COMPARE_NEW`(IN P_DATA_DATE VARCHAR(10))
BEGIN
  DECLARE V_PROC_NAME     VARCHAR(80)   DEFAULT 'EDW.P_TRS_BUDGET_INCOME_COMPARE_NEW.PRC';
  DECLARE V_START_TIME    CHAR(19)      DEFAULT NOW();
  DECLARE V_STEP_ID       INT           DEFAULT 0;
  DECLARE S_DATA_DATE     VARCHAR(8)	DEFAULT	DATE_FORMAT(P_DATA_DATE,'%Y-%m');
  
  DECLARE done INT DEFAULT 0;
  DECLARE V_DATA_DATE     VARCHAR(8);
  DECLARE cur CURSOR FOR
  SELECT DISTINCT data_date FROM stg.trs_tmis_budget_income_provinces WHERE data_date = DATE_FORMAT(P_DATA_DATE,'%Y%m') ORDER BY data_date;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
 
     DECLARE EXIT HANDLER FOR SQLEXCEPTION
   BEGIN
       GET DIAGNOSTICS CONDITION 1 @V_RETURN_CODE = RETURNED_SQLSTATE ,@V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(S_DATA_DATE,V_START_TIME,NOW(),V_PROC_NAME,V_STEP_ID,@V_RETURN_CODE,@V_ERROR_MSG);
   END; 
  
  
  OPEN cur;
  WHILE
    done <> 1 DO FETCH cur INTO V_DATA_DATE;
    IF done <> 1
    THEN 
SELECT V_DATA_DATE;    
    SET V_STEP_ID = 1;

    
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = V_DATA_DATE;
SET V_STEP_ID = 2;
INSERT INTO EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM(101_TATE),4)
	,SUM(101_RANK)
	,ROWS_ID
FROM 
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	@rank:=@rank+1 AS T010101_RANK,
	AA.101_TATE,
	AA.101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS 101_TATE,
	'' AS 101_RANK,
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA ,(SELECT @rank:=0) BB
UNION ALL
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA.101_TATE,
	@rank2:=@rank2+1  AS 101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS 101_TATE,
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
,(SELECT @tate:=NULL,@rank:=0) c
WHERE A.DATA_DATE = V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY 101_TATE DESC
) AA ,(SELECT @rank2:=0) BB
) 
)A
GROUP BY 
        PROJECT;
        
 SET V_STEP_ID = 3;       
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = CONCAT(YEAR(CONCAT(V_DATA_DATE,'01')),'Q',QUARTER(CONCAT(V_DATA_DATE,'01')));
 SET V_STEP_ID = 4;
INSERT INTO EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM(101_TATE),4)
	,SUM(101_RANK)
	,ROWS_ID
FROM 
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	@rank:=@rank+1 AS T010101_RANK,
	AA.101_TATE,
	AA.101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS 101_TATE,
	'' AS 101_RANK,
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA ,(SELECT @rank:=0) BB
UNION ALL
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA.101_TATE,
	@rank2:=@rank2+1  AS 101_RANK,
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS 101_TATE,
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
,(SELECT @tate:=NULL,@rank:=0) c
WHERE a.data_Date =V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY 101_TATE DESC
) AA ,(SELECT @rank2:=0) BB
) 
)A
GROUP BY 
        PROJECT;
    END IF;
  END WHILE;
  CLOSE cur;
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`p_trs_budget_income_cq`
DROP PROCEDURE IF EXISTS `edw`.`p_trs_budget_income_cq`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `p_trs_budget_income_cq`(IN s_date DATE,IN edate DATE)
BEGIN
  
  DECLARE V_START_TIME    CHAR(19)      DEFAULT NOW();
  DECLARE V_PROC_NAME     VARCHAR(80)   DEFAULT 'EDW.p_trs_budget_income_cq.PRC';
  DECLARE V_STEP_ID       INT           DEFAULT 0;
  
  
  
  
  WHILE s_date <= edate
  DO

  DELETE FROM edw.trs_d003_tr_budget_income WHERE D_REPORTDATE = s_date;
	  SET V_STEP_ID =2;

INSERT edw.trs_d003_tr_budget_income
(
D_REPORTDATE         ,           
S_TAXORGCODE         ,           
S_TRECODE            ,           
C_BUDGETTYPE         ,           
C_BUDGETLEVEL        ,           
S_BUDGETSUBJECTCODE  ,           
S_BUDGETSUBJECTNAME  ,           
F_DAYAMT             ,           
F_TENDAYAMT          ,           
F_MONTHAMT           ,           
F_QUARTERAMT         ,           
F_YEARAMT            ,           
C_CREATETIME         
)
SELECT 
D_REPORTDATE,
 S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME,
SUM(F_DAYAMT) F_DAYAMT,
SUM(F_TENDAYAMT) F_TENDAYAMT,
SUM(F_MONTHAMT) F_MONTHAMT,
SUM(F_QUARTERAMT) F_QUARTERAMT,
SUM(F_YEARAMT) F_YEARAMT,
CURRENT_TIMESTAMP  AS C_CREATETIME
FROM edw.trs_d003_tr_budget_income_temp a

WHERE 

  C_BUDGETTYPE = '1' 
AND S_TAXORGCODE = '000000000000'
AND s_trecode = '2200000000'

AND a.D_REPORTDATE = s_date
GROUP BY 
D_REPORTDATE,
S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME
;
    
INSERT INTO edw.trs_d003_tr_budget_income
(
D_REPORTDATE         ,           
S_TAXORGCODE         ,           
S_TRECODE            ,           
C_BUDGETTYPE         ,           
C_BUDGETLEVEL        ,           
S_BUDGETSUBJECTCODE  ,           
S_BUDGETSUBJECTNAME  ,           
F_DAYAMT             ,           
F_TENDAYAMT          ,           
F_MONTHAMT           ,           
F_QUARTERAMT         ,           
F_YEARAMT            ,           
C_CREATETIME         
)
 
SELECT 
D_REPORTDATE,
S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME,
SUM(F_DAYAMT) F_DAYAMT,
SUM(F_TENDAYAMT) F_TENDAYAMT,
SUM(F_MONTHAMT) F_MONTHAMT,
SUM(F_QUARTERAMT) F_QUARTERAMT,
SUM(F_YEARAMT) F_YEARAMT,
CURRENT_TIMESTAMP  AS C_CREATETIME
FROM 
(
SELECT 
D_REPORTDATE,
'XXXXXXXXXXXX' S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME,
SUM(F_DAYAMT) F_DAYAMT,
SUM(F_TENDAYAMT) F_TENDAYAMT,
SUM(F_MONTHAMT) F_MONTHAMT,
SUM(F_QUARTERAMT) F_QUARTERAMT,
SUM(F_YEARAMT) F_YEARAMT
FROM edw.trs_d003_tr_budget_income_temp a

WHERE   C_BUDGETLEVEL  IN  ('0','1','2')
 AND C_BUDGETTYPE = '1' 
AND S_TAXORGCODE = '000000000000'
AND s_trecode = '2200000000'

AND a.D_REPORTDATE = s_date
GROUP BY 
D_REPORTDATE,
S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME
UNION ALL
SELECT 
D_REPORTDATE,
'XXXXXXXXXXXX' S_TAXORGCODE,
'2200000000' S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME,
-1*SUM(F_DAYAMT) F_DAYAMT,
-1*SUM(F_TENDAYAMT) F_TENDAYAMT,
-1*SUM(F_MONTHAMT) F_MONTHAMT,
-1*SUM(F_QUARTERAMT) F_QUARTERAMT,
-1*SUM(F_YEARAMT) F_YEARAMT
FROM edw.trs_d003_tr_budget_income_temp a
WHERE   C_BUDGETLEVEL in  ('0','1','2')   
  and    C_BUDGETTYPE =  '1' 
  AND S_TRECODE <> '2200000000'
AND S_TAXORGCODE <> '000000000000'







AND a.D_REPORTDATE = s_date
GROUP BY 
D_REPORTDATE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME
) ss
GROUP BY 
D_REPORTDATE,
S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME
;
INSERT edw.trs_d003_tr_budget_income
(
D_REPORTDATE         ,           
S_TAXORGCODE         ,           
S_TRECODE            ,           
C_BUDGETTYPE         ,           
C_BUDGETLEVEL        ,           
S_BUDGETSUBJECTCODE  ,           
S_BUDGETSUBJECTNAME  ,           
F_DAYAMT             ,           
F_TENDAYAMT          ,           
F_MONTHAMT           ,           
F_QUARTERAMT         ,           
F_YEARAMT            ,           
C_CREATETIME         
)
SELECT 
D_REPORTDATE,
 S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME,
SUM(F_DAYAMT) F_DAYAMT,
SUM(F_TENDAYAMT) F_TENDAYAMT,
SUM(F_MONTHAMT) F_MONTHAMT,
SUM(F_QUARTERAMT) F_QUARTERAMT,
SUM(F_YEARAMT) F_YEARAMT,
CURRENT_TIMESTAMP  AS C_CREATETIME
FROM edw.trs_d003_tr_budget_income_temp a

WHERE  
  C_BUDGETTYPE = '1' 
AND S_TAXORGCODE <> '000000000000'
AND s_trecode <> '2200000000'

AND a.D_REPORTDATE = s_date
GROUP BY 
D_REPORTDATE,
S_TAXORGCODE,
S_TRECODE,
C_BUDGETTYPE,
C_BUDGETLEVEL,
S_BUDGETSUBJECTCODE,
S_BUDGETSUBJECTNAME
;
  CALL ETL.EDW_PROC_TRACE_LOG(DATE_FORMAT(s_date,'%Y%m%d'),V_START_TIME,NOW(),V_PROC_NAME,V_STEP_ID,ROW_COUNT());
 
 
 
  
  SET s_date = DATE_ADD(s_date,INTERVAL 1 DAY);
  COMMIT;
  END WHILE;
END
$$
DELIMITER ;

-- PROCEDURE `edw`.`p_trs_budget_new`
DROP PROCEDURE IF EXISTS `edw`.`p_trs_budget_new`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `p_trs_budget_new`()
BEGIN
  delete
  from
    edw.`cm_guoku_bdgorg`;
  INSERT INTO edw.cm_guoku_bdgorg (
    S_BDGORGTRECODE,
    S_TRECODE,
    S_BDGORGCODE,
    S_BDGORGNAME
  )
  SELECT DISTINCT
    CONCAT(S_TRECODE, S_BDGORGCODE) AS S_BDGORGTRECODE,
    S_TRECODE,
    S_BDGORGCODE,
    S_BDGORGNAME
  FROM
    adm.`trs_stat_agentbankpay_detail`;
  commit;
END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_TRS_FINANCE_TAX_STATIS`
DROP PROCEDURE IF EXISTS `edw`.`P_TRS_FINANCE_TAX_STATIS`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `P_TRS_FINANCE_TAX_STATIS`(in V_DATA_DATE VARCHAR(10))
BEGIN
DECLARE v_proc_name VARCHAR(50)   DEFAULT 'EDW.P_TRS_FINANCE_TAX_STATIS';
DECLARE V_STEP_ID   INT 	  DEFAULT '0';
DECLARE P_DATA_DATE VARCHAR(50)     DEFAULT DATE_FORMAT(V_DATA_DATE,'%Y-%m');
DECLARE V_START_TIME VARCHAR(50)    DEFAULT NOW();
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
       GET DIAGNOSTICS CONDITION 1 @V_RETURN_CODE = RETURNED_SQLSTATE ,@V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),v_proc_name,V_STEP_ID,@V_RETURN_CODE,@V_ERROR_MSG);
END;
SET V_STEP_ID = 1;
DELETE FROM EDW.TRS_FINANCE_TAX_STATIS WHERE D_ACCT = DATE_FORMAT(V_DATA_DATE,'%Y-%m-%d');
SET V_STEP_ID = 2;
INSERT INTO EDW.TRS_FINANCE_TAX_STATIS
SELECT
	 AA.DATA_DATE      
	,AA.T_AREA_NO   
	,AA.T_AREA_DSCR 
	,AA.SERVICE_TYPE
	,AA.ROWS_ID
	,AA.UP_YEAR     
	,(AA.UP_YEAR/BB.UP_YEAR)     AS UP_YEAR_PP  
	,AA.DOWN_YEAR   
	,(AA.DOWN_YEAR/BB.DOWN_YEAR) AS DOWN_YEAR_PP
	,AA.DOWN_YEAR_Y 
FROM
(
SELECT 
	 A.DATA_DATE      
	,A.AREA_NO         AS T_AREA_NO   
	,C.AREA_DSCR       AS T_AREA_DSCR 
	,A.SERVICE_TYPE
	,A.ROWS_ID
	,SUM(A.UP_YEAR)    AS UP_YEAR     
	,SUM(A.DOWN_YEAR)  AS DOWN_YEAR   
	,(SUM(A.DOWN_YEAR)-SUM(B.DOWN_YEAR))/SUM(B.DOWN_YEAR) 		   AS DOWN_YEAR_Y  
FROM ODS.CQ_FINANCE_TAX_STATIS A 
LEFT JOIN ODS.CQ_FINANCE_TAX_STATIS B 
       ON DATE_FORMAT(B.DATA_DATE,'%Y-%m-%d') = DATE_SUB(A.DATA_DATE,INTERVAL 1 YEAR) 
       AND A.AREA_NO = B.AREA_NO 
       AND A.ORG_NO = B.ORG_NO 
       AND A.SERVICE_TYPE = B.SERVICE_TYPE 
LEFT JOIN DMCODE.T_AREA_CODE C 
       ON A.AREA_NO = C.AREA_NO_ID 
WHERE A.DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y-%m-%d') 
GROUP BY 
	A.DATA_DATE,  
	A.AREA_NO, 
	A.SERVICE_TYPE,
	A.ROWS_ID
) AA 
LEFT JOIN 
( 
SELECT  
	DATA_DATE, 
	AREA_NO, 
	SUM(UP_YEAR)	AS UP_YEAR, 
	SUM(DOWN_YEAR)  AS DOWN_YEAR
FROM ODS.CQ_FINANCE_TAX_STATIS 
WHERE DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y-%m-%d') 
  AND SERVICE_TYPE = '金融业合计' 
GROUP BY 
	DATA_DATE, 
	AREA_NO, 
	SERVICE_TYPE 
) BB  
      ON AA.T_AREA_NO = BB.AREA_NO ;
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_TRS_FINANCE_TAX_STATIS_NEW`
DROP PROCEDURE IF EXISTS `edw`.`P_TRS_FINANCE_TAX_STATIS_NEW`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `P_TRS_FINANCE_TAX_STATIS_NEW`(IN V_DATA_DATE VARCHAR(10))
BEGIN
DECLARE v_proc_name VARCHAR(50)   DEFAULT 'EDW.P_TRS_FINANCE_TAX_STATIS_NEW';
DECLARE V_STEP_ID   INT 	  DEFAULT '0';
DECLARE P_DATA_DATE VARCHAR(50)     DEFAULT DATE_FORMAT(V_DATA_DATE,'%Y-%m');
DECLARE V_START_TIME VARCHAR(50)    DEFAULT NOW();
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
       GET DIAGNOSTICS CONDITION 1 @V_RETURN_CODE = RETURNED_SQLSTATE ,@V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),v_proc_name,V_STEP_ID,@V_RETURN_CODE,@V_ERROR_MSG);
END;
SET V_STEP_ID = 1;
DELETE FROM EDW.TRS_FINANCE_TAX_STATIS WHERE    D_ACCT = CONCAT(
      YEAR(V_DATA_DATE),
      'Q',
      QUARTER(V_DATA_DATE)
    )
;
SET V_STEP_ID = 2;
INSERT INTO EDW.TRS_FINANCE_TAX_STATIS
SELECT
CONCAT(
      YEAR(CONCAT(AA.DATA_DATE,'01')),
      'Q',
      QUARTER(CONCAT(AA.DATA_DATE,'01'))
    ) AS D_ACCT     
	,AA.T_AREA_NO   
	,AA.T_AREA_DSCR 
	,AA.SERVICE_TYPE
	,AA.ROWS_ID
	,AA.UP_YEAR     
	,(AA.UP_YEAR/BB.UP_YEAR)     AS UP_YEAR_PP  
	,AA.DOWN_YEAR   
	,(AA.DOWN_YEAR/BB.DOWN_YEAR) AS DOWN_YEAR_PP
	,AA.DOWN_YEAR_Y 
FROM
(
SELECT 
	 A.DATA_DATE      
	,A.AREA_NO         AS T_AREA_NO   
	,C.AREA_DSCR       AS T_AREA_DSCR 
	,A.SERVICE_TYPE
	,A.ROWS_ID
	,SUM(A.UP_YEAR)    AS UP_YEAR     
	,SUM(A.DOWN_YEAR)  AS DOWN_YEAR   
	,(SUM(A.DOWN_YEAR)-SUM(B.DOWN_YEAR))/SUM(B.DOWN_YEAR) 		   AS DOWN_YEAR_Y  
FROM ODS.CQ_FINANCE_TAX_STATIS A 
LEFT JOIN ODS.CQ_FINANCE_TAX_STATIS B 
       ON B.DATA_DATE = DATE_FORMAT(DATE_SUB(DATE_FORMAT(CONCAT(A.DATA_DATE,'01'),'%Y%m%d'),INTERVAL 1 YEAR) ,'%Y%m')
       AND A.AREA_NO = B.AREA_NO 
       AND A.ORG_NO = B.ORG_NO 
       AND A.SERVICE_TYPE = B.SERVICE_TYPE 
LEFT JOIN DMCODE.T_AREA_CODE C 
       ON A.AREA_NO = C.AREA_NO_ID 
WHERE A.DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y%m') 
GROUP BY 
	A.DATA_DATE,  
	A.AREA_NO, 
	A.SERVICE_TYPE,
	A.ROWS_ID
) AA 
LEFT JOIN 
( 
SELECT  
	DATA_DATE, 
	AREA_NO, 
	SUM(UP_YEAR)	AS UP_YEAR, 
	SUM(DOWN_YEAR)  AS DOWN_YEAR
FROM ODS.CQ_FINANCE_TAX_STATIS 
WHERE DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y%m') 
  AND SERVICE_TYPE = '金融业合计' 
GROUP BY 
	DATA_DATE, 
	AREA_NO, 
	SERVICE_TYPE 
) BB  
      ON AA.T_AREA_NO = BB.AREA_NO ;
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_trs_kyd_industry`
DROP PROCEDURE IF EXISTS `edw`.`P_trs_kyd_industry`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `P_trs_kyd_industry`(IN V_DATA_DATE VARCHAR(10))
BEGIN

DELETE FROM EDW.trs_kyd_industry WHERE D_ACCT = V_DATA_DATE;
INSERT INTO EDW.trs_kyd_industry
SELECT
   det.S_INTREDATE                      												AS d_acct
  ,det.S_TRECODE                                                AS S_TRECODE
  ,dim.guoku_dscr                                              AS S_TREDSCR
  ,''
  ,''
  ,det.ETPCODE
  ,INFO.ENTNAME
  ,indus.LEV_1_ID
  ,indus.LEV_1_DSCR
  ,indus.LEV_2_ID
  ,indus.LEV_2_DSCR
  ,indus.LEV_3_ID
  ,indus.LEV_3_DSCR
  ,indus.LEV_4_ID
  ,indus.LEV_4_DSCR
  ,det.S_BDGSBTCODE
  ,''
  ,det.F_AMT				                                                   AS F_AMT_YEAR
FROM ods.tv_fin_income_detail det
LEFT JOIN ODS.TRS_INFO_ENTERPRISES INFO
     ON DET.TAXPAYCODE = INFO.UNISCID
LEFT JOIN EDW.CM_CLR_INDUSTRY_INFO INDUS
     ON INFO.INDUSTRYCO = INDUS.LEV_4_ID
LEFT JOIN DMCODE.CM_GUOKU_DIMNSN DIM
     ON DET.S_TRECODE = DIM.guoku_id
WHERE DET.S_INTREDATE  = V_DATA_DATE
    
    
		AND DET.cfbz = '0';
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_trs_kyd_industry_0911`
DROP PROCEDURE IF EXISTS `edw`.`P_trs_kyd_industry_0911`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `P_trs_kyd_industry_0911`(IN V_DATA_DATE VARCHAR(10))
BEGIN

DELETE FROM EDW.trs_kyd_industry_linshi;
INSERT INTO EDW.trs_kyd_industry_linshi
SELECT
   det.S_INTREDATE 				AS d_acct
  ,det.S_TRECODE     AS S_TRECODE
  ,''  AS a
  ,''  as b
  ,''  as c
  ,det.TAXPAYCODE
  ,DET.TAXPAYNAME
  ,''   as d
  ,''   as e
  ,''   as f
  ,''   as g
  ,''   as h
  ,''   as i
  ,''   as j
  ,''   as k
  ,det.S_BDGSBTCODE
  ,'' as l
  ,det.F_AMT    AS F_AMT_YEAR
FROM ods.tv_fin_income_detail det
WHERE DET.S_INTREDATE like  CONCAT(DATE_FORMAT(V_DATA_DATE,'%Y%m'),'%')
    
    
		AND DET.cfbz = '0';
DELETE FROM EDW.trs_kyd_industry WHERE D_ACCT like  CONCAT(DATE_FORMAT(V_DATA_DATE,'%Y%m'),'%');
INSERT INTO EDW.trs_kyd_industry
SELECT
		DISTINCT
   det.d_acct                      												AS d_acct
  ,det.S_TRECODE                                                AS S_TRECODE
  ,dim.guoku_dscr                                              AS S_TREDSCR
  ,''   as a
  ,''   as b
  ,det.ETPCODE
  ,INFO.ENTNAME
  ,indus.LEV_1_ID
  ,indus.LEV_1_DSCR
  ,indus.LEV_2_ID
  ,indus.LEV_2_DSCR
  ,indus.LEV_3_ID
  ,indus.LEV_3_DSCR
  ,indus.LEV_4_ID
  ,indus.LEV_4_DSCR
  ,det.S_BDGSBTCODE
  ,''   as c
  ,det.F_AMT				                                                   AS F_AMT_YEAR
FROM EDW.trs_kyd_industry_linshi det
LEFT JOIN ODS.trs_info_enterprises INFO
     ON DET.ETPNAME = INFO.ENTNAME
LEFT JOIN EDW.CM_CLR_INDUSTRY_INFO INDUS
     ON INFO.INDUSTRYCO = INDUS.LEV_4_ID
LEFT JOIN DMCODE.CM_GUOKU_DIMNSN DIM
     ON DET.S_TRECODE = DIM.guoku_id;
	END
$$
DELIMITER ;

-- PROCEDURE `edw`.`P_trs_kyd_industry_s`
DROP PROCEDURE IF EXISTS `edw`.`P_trs_kyd_industry_s`;
DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `P_trs_kyd_industry_s`(IN V_DATA_DATE VARCHAR(10))
BEGIN

DELETE FROM EDW.trs_kyd_industry_copy1 WHERE D_ACCT = V_DATA_DATE;
INSERT INTO EDW.trs_kyd_industry_copy1
SELECT
   det.S_INTREDATE                      												AS d_acct
  ,det.S_TRECODE                                                AS S_TRECODE
  ,dim.guoku_dscr                                              AS S_TREDSCR
  ,''
  ,''
  ,det.ETPCODE
  ,INFO.ENTNAME
  ,indus.LEV_1_ID
  ,indus.LEV_1_DSCR
  ,indus.LEV_2_ID
  ,indus.LEV_2_DSCR
  ,indus.LEV_3_ID
  ,indus.LEV_3_DSCR
  ,indus.LEV_4_ID
  ,indus.LEV_4_DSCR
  ,det.S_BDGSBTCODE
  ,''
  ,det.F_AMT				                                                   AS F_AMT_YEAR
FROM  ODS.TRS_INFO_ENTERPRISES INFO
LEFT JOIN EDW.CM_CLR_INDUSTRY_INFO INDUS
     ON INFO.INDUSTRYCO = INDUS.LEV_4_ID
LEFT JOIN ods.tv_fin_income_detail det
     ON  INFO.UNISCID = DET.TAXPAYCODE 
LEFT JOIN DMCODE.CM_GUOKU_DIMNSN DIM
     ON DET.S_TRECODE = DIM.guoku_id
WHERE DET.S_INTREDATE  like '202106'
    AND DET.S_BDGSBTCODE LIKE '101%'
    AND DET.S_TAXORGCODE NOT LIKE '%45%'
		AND DET.cfbz = '0';
	END
$$
DELIMITER ;


-- Included procedures:
--   edw.P_TRS_BUDGET_INCOME_COMPARE
--   edw.P_TRS_BUDGET_INCOME_COMPARE_NEW
--   edw.P_TRS_FINANCE_TAX_STATIS
--   edw.P_TRS_FINANCE_TAX_STATIS_NEW
