#postgresql
diver_name=org.postgresql.Driver
url=jdbc:postgresql://100.71.11.54:25432/gk_data_analysis?currentSchema=visual_screen,public
username=vastbase_test
password=B$S8*^75foTnE*z1
database_name=gk_data_analysis

#oracle
#diver_name=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@192.168.1.200:1521:ORCL
#username=scott
#password=tiger
#database_name=ORCL

#mysql
#diver_name=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://localhost:3306/jeecg-boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#username=root
#password=root
#database_name=jeecg-boot

#SQLServer2005\u4ee5\u4e0a
#diver_name=org.hibernate.dialect.SQLServerDialect
#url=jdbc:sqlserver://192.168.1.200:1433;DatabaseName=jeecg
#username=sa
#password=SA
#database_name=jeecg