-- Generated from document/psql/mysql/adm.sql; do not edit by hand.
CREATE SCHEMA IF NOT EXISTS adm;
SET search_path TO adm, public;

CREATE INDEX IF NOT EXISTS ana_sust_mth_enterprise_survey_enterprise_id_index ON adm.ana_sust_mth_enterprise_survey (enterprise_id);
CREATE INDEX IF NOT EXISTS ana_sust_mth_enterprise_survey_data_date_index ON adm.ana_sust_mth_enterprise_survey (data_date);
CREATE INDEX IF NOT EXISTS dis_file_process_node_file_id ON adm.dis_file_process_node (file_id, node_no);
CREATE INDEX IF NOT EXISTS px_cx_mth_cash_servinfo_data_date ON adm.px_cx_mth_cash_servinfo (trade_date);
CREATE INDEX IF NOT EXISTS py_cx_cash_servinfo_village_code ON adm.py_cx_cash_servinfo (village_code);
CREATE INDEX IF NOT EXISTS py_cx_dw_cash_tradelog_data_date ON adm.py_cx_dw_cash_tradelog (data_date);
CREATE INDEX IF NOT EXISTS py_cx_dw_cash_tradelog_area_no ON adm.py_cx_dw_cash_tradelog (area_no);
CREATE INDEX IF NOT EXISTS py_cx_dw_cash_tradelog_org_no ON adm.py_cx_dw_cash_tradelog (org_no);
CREATE INDEX IF NOT EXISTS py_cx_dw_cash_tradelog_bank_type ON adm.py_cx_dw_cash_tradelog (bank_type);
CREATE INDEX IF NOT EXISTS py_cx_dw_cash_tradelog_tyade_type ON adm.py_cx_dw_cash_tradelog (tyade_type);
CREATE INDEX IF NOT EXISTS py_cx_dw_envbld_hf_wd_data_date ON adm.py_cx_dw_envbld_hf_wd (data_date);
CREATE INDEX IF NOT EXISTS py_cx_dw_envbld_hf_wd_area_no ON adm.py_cx_dw_envbld_hf_wd (area_no);
CREATE INDEX IF NOT EXISTS py_cx_dw_envbld_hf_wd_org_no ON adm.py_cx_dw_envbld_hf_wd (org_no);
CREATE INDEX IF NOT EXISTS py_cx_dw_envbld_hf_wd_bank_type ON adm.py_cx_dw_envbld_hf_wd (bank_type);
CREATE INDEX IF NOT EXISTS py_cx_dw_envbld_hf_wd_state ON adm.py_cx_dw_envbld_hf_wd (state);
CREATE INDEX IF NOT EXISTS py_cx_map_zlarea_trade_date ON adm.py_cx_map_zlarea (trade_date);
CREATE INDEX IF NOT EXISTS py_cx_map_zlcity_trade_date ON adm.py_cx_map_zlcity (trade_date);
CREATE INDEX IF NOT EXISTS py_cx_yc_check_detail_shop_num_index ON adm.py_cx_yc_check_detail (shop_num);
CREATE INDEX IF NOT EXISTS py_cx_yc_check_detail_trade_date_index ON adm.py_cx_yc_check_detail (trade_date);
CREATE INDEX IF NOT EXISTS py_cx_yc_check_detail_yc_big_index ON adm.py_cx_yc_check_detail (yc_big);
CREATE INDEX IF NOT EXISTS py_cx_yc_check_detail_yc_details_index ON adm.py_cx_yc_check_detail (yc_detail);
CREATE INDEX IF NOT EXISTS rpt_v_half_dimnsn_code_mth_dimnsn_in_index ON adm.rpt_v_half_dimnsn_code (fiscal_id);
CREATE INDEX IF NOT EXISTS rpt_v_mth_dimnsn_code_mth_dimnsn_in_index ON adm.rpt_v_mth_dimnsn_code (fiscal_id);
CREATE INDEX IF NOT EXISTS rpt_v_org_dimnsn_code_org_id_indx ON adm.rpt_v_org_dimnsn_code (org_id);
CREATE INDEX IF NOT EXISTS rpt_v_qtr_dimnsn_code_mth_dimnsn_in_index ON adm.rpt_v_qtr_dimnsn_code (fiscal_id);
CREATE INDEX IF NOT EXISTS rpt_v_year_dimnsn_code_mth_dimnsn_in_index ON adm.rpt_v_year_dimnsn_code (fiscal_id);
CREATE INDEX IF NOT EXISTS t_sys_template_file_dept_template_file_id ON adm.t_sys_template_file_dept (template_file_id, department, biz_type_id);
CREATE INDEX IF NOT EXISTS t_sys_template_file_dept_template_file_id1 ON adm.t_sys_template_file_dept (template_file_id, department, biz_type_id);
CREATE INDEX IF NOT EXISTS t_sys_template_file_dept_template_file_id2 ON adm.t_sys_template_file_dept (template_file_id, department, biz_type_id);
CREATE INDEX IF NOT EXISTS t_sys_template_file_dept_template_file_id3 ON adm.t_sys_template_file_dept (template_file_id, department);
CREATE INDEX IF NOT EXISTS t_sys_template_file_org_template_file_id ON adm.t_sys_template_file_org (template_file_id, org_id);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_date ON adm.trs_budget_function_income_daily (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_trecode ON adm.trs_budget_function_income_daily (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_code_4 ON adm.trs_budget_function_income_daily (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_code_1 ON adm.trs_budget_function_income_daily (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_code_2 ON adm.trs_budget_function_income_daily (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_daily_index_code_3 ON adm.trs_budget_function_income_daily (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_date ON adm.trs_budget_function_income_monthly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_trecode ON adm.trs_budget_function_income_monthly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_code_4 ON adm.trs_budget_function_income_monthly (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_code_1 ON adm.trs_budget_function_income_monthly (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_code_2 ON adm.trs_budget_function_income_monthly (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_monthly_index_code_3 ON adm.trs_budget_function_income_monthly (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_date ON adm.trs_budget_function_income_yearly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_trecode ON adm.trs_budget_function_income_yearly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_code_4 ON adm.trs_budget_function_income_yearly (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_code_1 ON adm.trs_budget_function_income_yearly (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_code_2 ON adm.trs_budget_function_income_yearly (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_income_yearly_index_code_3 ON adm.trs_budget_function_income_yearly (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_date ON adm.trs_budget_function_payout_daily (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_trecode ON adm.trs_budget_function_payout_daily (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_code_4 ON adm.trs_budget_function_payout_daily (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_code_1 ON adm.trs_budget_function_payout_daily (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_code_2 ON adm.trs_budget_function_payout_daily (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_daily_index_code_3 ON adm.trs_budget_function_payout_daily (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_date ON adm.trs_budget_function_payout_monthly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_trecode ON adm.trs_budget_function_payout_monthly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_code_4 ON adm.trs_budget_function_payout_monthly (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_code_1 ON adm.trs_budget_function_payout_monthly (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_code_2 ON adm.trs_budget_function_payout_monthly (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_monthly_index_code_3 ON adm.trs_budget_function_payout_monthly (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_date ON adm.trs_budget_function_payout_yearly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_trecode ON adm.trs_budget_function_payout_yearly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_code_4 ON adm.trs_budget_function_payout_yearly (subject_code_4);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_code_1 ON adm.trs_budget_function_payout_yearly (fun_class_code_1);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_code_2 ON adm.trs_budget_function_payout_yearly (fun_class_code_2);
CREATE INDEX IF NOT EXISTS trs_budget_function_payout_yearly_index_code_3 ON adm.trs_budget_function_payout_yearly (fun_class_code_3);
CREATE INDEX IF NOT EXISTS trs_budget_limit_income_daily_index_accept ON adm.trs_budget_limit_income_daily (d_accept);
CREATE INDEX IF NOT EXISTS trs_budget_limit_income_daily_index_trecode ON adm.trs_budget_limit_income_daily (s_taxpaycode);
CREATE INDEX IF NOT EXISTS trs_budget_limit_income_daily_index_aimtrecode ON adm.trs_budget_limit_income_daily (s_aimtrecode);
CREATE INDEX IF NOT EXISTS trs_budget_limit_income_daily_index_bdsbcode ON adm.trs_budget_limit_income_daily (s_bdgsbtcode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_daily_index_date ON adm.trs_budget_summary_all_daily (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_daily_index_trecode ON adm.trs_budget_summary_all_daily (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_daily_index_level ON adm.trs_budget_summary_all_daily (c_budgetlevel);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_daily_index_bdgsbcode ON adm.trs_budget_summary_all_daily (s_budgetsubjectcode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_monthly_index_date ON adm.trs_budget_summary_all_monthly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_monthly_index_trecode ON adm.trs_budget_summary_all_monthly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_monthly_index_level ON adm.trs_budget_summary_all_monthly (c_budgetlevel);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_monthly_index_bdgsbcode ON adm.trs_budget_summary_all_monthly (s_budgetsubjectcode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_yearly_index_date ON adm.trs_budget_summary_all_yearly (d_reportdate);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_yearly_index_trecode ON adm.trs_budget_summary_all_yearly (s_trecode);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_yearly_index_level ON adm.trs_budget_summary_all_yearly (c_budgetlevel);
CREATE INDEX IF NOT EXISTS trs_budget_summary_all_yearly_index_bdgsbcode ON adm.trs_budget_summary_all_yearly (s_budgetsubjectcode);
CREATE INDEX IF NOT EXISTS trs_kyd_enterprise_index ON adm.trs_kyd_enterprise (d_acct, s_trecode, procode, proname, mark);
CREATE INDEX IF NOT EXISTS trs_kyd_enterprise_rank_index ON adm.trs_kyd_enterprise_rank (d_acct, s_trecode);
CREATE INDEX IF NOT EXISTS trs_kyd_enterprise_rank_copy_index ON adm.trs_kyd_enterprise_rank_copy (d_acct, s_trecode);
CREATE INDEX IF NOT EXISTS trs_kyd_industry_index ON adm.trs_kyd_industry (d_acct, s_trecode, mark);
CREATE INDEX IF NOT EXISTS trs_kyd_industry_comprehensive_index ON adm.trs_kyd_industry_comprehensive (d_acct);
CREATE INDEX IF NOT EXISTS trs_stat_agentbankpay_detail_date ON adm.trs_stat_agentbankpay_detail (s_entrustdate);
CREATE INDEX IF NOT EXISTS trs_stat_agentbankpay_detail_guoku ON adm.trs_stat_agentbankpay_detail (s_trecode);
