-- ADM routine dependency closure adapted from the production MySQL routines.
-- Load after 013/014 and before 015_adm_routines_init.sql.

DROP PROCEDURE IF EXISTS edw.P_CM_SUST_UPDATE;

CREATE PROCEDURE edw.P_CM_SUST_UPDATE()
AS
BEGIN

TRUNCATE edw.cm_sust_equity_class;
TRUNCATE edw.cm_sust_crcs;
TRUNCATE edw.cm_sust_other_ways;
TRUNCATE edw.cm_sust_special_purpose;

INSERT INTO edw.cm_sust_equity_class
(
	EC_DSCR,
	TYPE
)
SELECT
	DISTINCT a.L2101 AS EC_DSCR,
	'A01'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a01 a
UNION ALL
SELECT
	DISTINCT a.Y2101 AS EC_DSCR,
	'A02'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a02 a;

INSERT INTO edw.cm_sust_crcs
(
	CRCS_DSCR,
	TYPE
)
SELECT
	DISTINCT a.L2102 AS CRCS_DSCR,
	'A01'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a01 a
UNION ALL
SELECT
	DISTINCT a.Y2102 AS CRCS_DSCR,
	'A02'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a02 a;

INSERT INTO edw.cm_sust_other_ways
(
	DSCR,
	TYPE
)
SELECT
	DISTINCT a.L2103 AS DSCR,
	'A01'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a01 a;

INSERT INTO edw.cm_sust_special_purpose
(
	SP_DSCR,
	TYPE
)
SELECT
	DISTINCT a.Y2103 AS SP_DSCR,
	'A01'            AS TYPE
FROM ods.sust_source_of_funds_detailed_a02 a;
    END;
/

DROP PROCEDURE IF EXISTS edw.P_SUST_SCIENCE_TECHNOLOGY_AND_FINANCE;

CREATE PROCEDURE edw.P_SUST_SCIENCE_TECHNOLOGY_AND_FINANCE(in V_BATCH_DATE varchar(10))
AS
	DONE             INT := FALSE;	
	V_DATA_DATE      VARCHAR(10);          
	CURSOR CUR_D_ACCT IS 	SELECT DISTINCT DATA_DATE  
	FROM ods.sust_science_technology_and_finance
	WHERE BATCH_DATE = V_BATCH_DATE;
BEGIN

	
    -- NOT FOUND handler replaced by explicit cursor %NOTFOUND checks below.
	
	OPEN CUR_D_ACCT;
	<<ENTLOOP>>
	LOOP
		FETCH CUR_D_ACCT INTO V_DATA_DATE;
		EXIT WHEN CUR_D_ACCT%NOTFOUND;
		IF DONE THEN
		EXIT ENTLOOP;
		END IF;

DELETE FROM edw.sust_science_technology_and_finance WHERE DATA_DATE = v_data_date;

INSERT INTO edw.sust_science_technology_and_finance 
SELECT
	a.AREA_NO,
	a.DATA_DATE,
	a.TABLE_NATURE,
	a.ORG_NO,
	a.ADD_DATE,
	a.ROWS_ID,
	a.BATCH_DATE,
	a.SHEET_ID,
	a.KPINAME,
	a.BALANCE,
	a.PREVIOUSBALANCE,
	a.BALANCE-a.PREVIOUSBALANCE     				AS LAST_MONTH,
	ROUND((a.BALANCE-a.PREVIOUSBALANCE)/a.PREVIOUSBALANCE,2) 	AS CHAIN_RATIO,
	a.BALANCE-IFNULL(b.BALANCE,0)					AS OF_YEAR,
	ROUND((a.BALANCE-b.BALANCE)/b.BALANCE,2) 			AS OF_YEAR_RATE,
	a.CHECKTERM
FROM
	ods.sust_science_technology_and_finance a
LEFT JOIN ods.sust_science_technology_and_finance b
	ON DATE_FORMAT(CONCAT(a.DATA_DATE,'01'),'%Y-%m-%d') = DATE_FORMAT(CONCAT(b.DATA_DATE,'01'),'%Y-01-01')
	AND a.KPINAME = b.KPINAME
WHERE a.DATA_DATE = v_data_date;

DELETE FROM edw.sust_science_technology_and_finance_temp WHERE data_Date = v_data_date;

INSERT INTO edw.sust_science_technology_and_finance_temp
SELECT
	a.AREA_NO,
	a.DATA_DATE,
	a.TABLE_NATURE,
	'000000000000'									AS ORG_NO,
	a.ADD_DATE,
	a.ROWS_ID,
	a.BATCH_DATE,
	a.SHEET_ID,
	a.KPINAME,
	SUM(a.BALANCE) 									AS BALANCE,
	SUM(a.PREVIOUSBALANCE)								AS PREVIOUSBALANCE,
	SUM(a.BALANCE)-SUM(a.PREVIOUSBALANCE)     					AS LAST_MONTH,
	ROUND((SUM(a.BALANCE)-SUM(a.PREVIOUSBALANCE))/SUM(a.PREVIOUSBALANCE),2)		AS CHAIN_RATIO,
	SUM(a.BALANCE)-SUM(b.BALANCE)							AS OF_YEAR,
	ROUND((SUM(a.BALANCE)-SUM(b.BALANCE))/SUM(b.BALANCE),2)				AS OF_YEAR_RATE,
	a.CHECKTERM
FROM
	ods.sust_science_technology_and_finance a
LEFT JOIN ods.sust_science_technology_and_finance b
	ON DATE_FORMAT(CONCAT(a.DATA_DATE,'01'),'%Y-%m-%d') = DATE_FORMAT(CONCAT(b.DATA_DATE,'01'),'%Y-01-01')
	AND a.KPINAME = b.KPINAME
WHERE a.DATA_DATE = v_data_date
GROUP BY
	a.KPINAME;
	
	


UPDATE edw.sust_science_technology_and_finance_temp temp
SET temp.BALANCE = (
	SELECT 
		ROUND(a.fenzi/b.fenmu,8)
	FROM
	(
		SELECT 
			ROUND(SUM(aa.c),8) AS fenzi 
		FROM 
		( 
		SELECT 
			SUM(CASE WHEN a.ROWS_ID = '55' THEN a.BALANCE END)*
			SUM(CASE WHEN a.ROWS_ID = '58' THEN a.BALANCE END)/100    AS  c
		FROM ods.sust_science_technology_and_finance a
		WHERE a.DATA_DATE = v_data_date
		GROUP BY
			a.DATA_DATE
			,a.ORG_NO
		) aa
	) a
	,
	(
	SELECT 
		SUM(CASE WHEN a.ROWS_ID = '55' THEN a.BALANCE END) AS  fenmu
	 FROM ods.sust_science_technology_and_finance a
	WHERE a.DATA_DATE = v_data_date
	GROUP BY
		a.DATA_DATE
	) b 
),

temp.PREVIOUSBALANCE = (
	SELECT 
		ROUND(a.fenzi/b.fenmu,8)
	FROM
	(
		SELECT 
		ROUND(SUM(aa.c),8) AS fenzi 
		FROM 
		( 
		SELECT 
			SUM(CASE WHEN a.ROWS_ID = '55' THEN a.PREVIOUSBALANCE END)*
			SUM(CASE WHEN a.ROWS_ID = '58' THEN a.PREVIOUSBALANCE END)/100    AS  c
		 FROM ods.sust_science_technology_and_finance a
		WHERE a.DATA_DATE = v_data_date
		GROUP BY
		    a.DATA_DATE
		   ,a.ORG_NO
		) aa
	) a
	,
	(
	SELECT 
		SUM(CASE WHEN a.ROWS_ID = '55' THEN a.PREVIOUSBALANCE END) AS  fenmu
	 FROM ods.sust_science_technology_and_finance a
	WHERE a.DATA_DATE = v_data_date
	GROUP BY
	    a.DATA_DATE
	) b
)
WHERE
	temp.DATA_DATE = v_data_date 
	AND temp.ROWS_ID = '58';
	
	

UPDATE edw.sust_science_technology_and_finance_temp a
  JOIN edw.sust_science_technology_and_finance_temp b
    ON DATE_FORMAT(CONCAT(a.DATA_DATE,'01'),'%Y-%m-%d') = DATE_FORMAT(CONCAT(b.DATA_DATE,'01'),'%Y-01-01')
   AND a.KPINAME = b.KPINAME
SET a.LAST_MONTH = (a.BALANCE-a.PREVIOUSBALANCE),
    a.CHAIN_RATIO = round((a.BALANCE-a.PREVIOUSBALANCE)/a.PREVIOUSBALANCE,2),
    a.OF_YEAR = a.BALANCE-b.BALANCE,
    a.OF_YEAR_RATE = round((a.BALANCE-b.BALANCE)/b.BALANCE,2)
WHERE a.data_date = v_data_date
  AND a.ROWS_ID = '58';
  
  

UPDATE edw.sust_science_technology_and_finance_temp  a
SET a.BALANCE = 
   (
	SELECT 
	MIN(r.BALANCE) 
	FROM edw.sust_science_technology_and_finance r
	WHERE DATA_DATE = V_DATA_DATE
	AND r.ROWS_ID = '59'
	AND r.ORG_NO <> '000000000000'
    )
WHERE A.DATA_DATE = V_DATA_DATE
AND a.ROWS_ID = '59';

UPDATE edw.sust_science_technology_and_finance_temp  a
SET a.BALANCE = 
(
	SELECT 
	MAX(r.BALANCE) 
	FROM edw.sust_science_technology_and_finance r
	WHERE R.DATA_DATE = V_DATA_DATE
  AND	r.ROWS_ID = '60'
	AND r.ORG_NO <> '000000000000'
)
WHERE A.DATA_DATE = V_DATA_DATE
AND a.ROWS_ID = '60';

DELETE FROM edw.sust_science_technology_and_finance 
WHERE DATA_DATE = v_data_date
and ORG_NO = '000000000000';

INSERT INTO edw.sust_science_technology_and_finance 
SELECT * FROM edw.sust_science_technology_and_finance_temp
WHERE data_date = v_data_date;
	END LOOP ENTLOOP;
	CLOSE CUR_D_ACCT;
	END;
/

DROP PROCEDURE IF EXISTS edw.p_sust_source_of_funds_detailed_a01;

CREATE PROCEDURE edw.p_sust_source_of_funds_detailed_a01()
AS
  v_data_date char(8) := date_format(now(), '%Y%m%d');
BEGIN
  DELETE FROM edw.SUST_SOURCE_OF_FUNDS_DETAILED_A01
  WHERE DATA_DATE in
    (SELECT
      a.DATA_DATE
    FROM
      ods.SUST_SOURCE_OF_FUNDS_DETAILED_A01 a
    WHERE a.BATCH_DATE = v_data_date
    );
    commit;
    
   insert into edw.SUST_SOURCE_OF_FUNDS_DETAILED_A01 
   select
   *
   from ods.SUST_SOURCE_OF_FUNDS_DETAILED_A01 b
   where b.DATA_DATE IN
    (SELECT
      t.DATA_DATE
    FROM
      ods.SUST_SOURCE_OF_FUNDS_DETAILED_A01 t
    WHERE t.BATCH_DATE = v_data_date
    );
    commit;
END;
/

DROP PROCEDURE IF EXISTS edw.P_SUST_SOURCE_OF_FUNDS_DETAILED_A02;

CREATE PROCEDURE edw.P_SUST_SOURCE_OF_FUNDS_DETAILED_A02()
AS
  v_data_date char(8) := date_format(now(), '%Y%m%d');
BEGIN
  DELETE FROM edw.SUST_SOURCE_OF_FUNDS_DETAILED_A02
  WHERE DATA_DATE in
    (SELECT
      a.DATA_DATE
    FROM
      ods.SUST_SOURCE_OF_FUNDS_DETAILED_A02 a
    WHERE a.BATCH_DATE = v_data_date
    );
    commit;
    
   insert into edw.SUST_SOURCE_OF_FUNDS_DETAILED_A02 
   select
   *
   from ods.SUST_SOURCE_OF_FUNDS_DETAILED_A02 b
   where b.DATA_DATE IN
    (SELECT
      t.DATA_DATE
    FROM
      ods.SUST_SOURCE_OF_FUNDS_DETAILED_A02 t
    WHERE t.BATCH_DATE = v_data_date
    );
    commit;
END;
/

DROP PROCEDURE IF EXISTS edw.p_transDataFromOdsToEdw_main;

CREATE PROCEDURE edw.p_transDataFromOdsToEdw_main()
AS
  flag INT := FALSE;
  areaNo VARCHAR (8);
  dataDate CHAR (8);
  TABLE_NATURE VARCHAR (50);
  orgNo VARCHAR (53);
  ADD_DATE TIMESTAMP;
  rowsId VARCHAR (100);
  BATCH_DATE CHAR (8);
  SHEET_ID VARCHAR (100);
  OCCURRENCE_ORG VARCHAR (512);
  BWBDEPOSIT varchar (40);
  RMBDEPOSIT VARCHAR (40);
  SAVINGSDEPOSIT VARCHAR (40);
  BWBLOAN VARCHAR (40);
  RMBLOAN VARCHAR (40);
  SHORTTERMLOAN VARCHAR (40);
  MEDIUMLONGTERMLOAN VARCHAR (40);
  PERSONALMLTERMLOAN VARCHAR (40);
  CURSOR cur IS   SELECT
    *
  FROM
    ods.sust_main_indicators_of_institutions
  WHERE 1 = 1 
  ;
BEGIN
    -- NOT FOUND handler replaced by explicit cursor %NOTFOUND checks below.
  OPEN cur;
  <<posLoop>>
  LOOP
    FETCH cur INTO areaNo,
    dataDate,
    TABLE_NATURE,
    orgNo,
    ADD_DATE,
    rowsId,
    BATCH_DATE,
    SHEET_ID,
    OCCURRENCE_ORG,
    BWBDEPOSIT,
    RMBDEPOSIT,
    SAVINGSDEPOSIT,
    BWBLOAN,
    RMBLOAN,
    SHORTTERMLOAN,
    MEDIUMLONGTERMLOAN,
    PERSONALMLTERMLOAN;
    EXIT WHEN cur%NOTFOUND;
    IF flag
    THEN EXIT posLoop;
    END IF;
    
    DELETE
    FROM
      edw.sust_main_indicators_of_institutions
    WHERE AREA_NO = areaNo
      AND ORG_NO = orgNo
      AND DATA_DATE = dataDate
      and ROWS_ID = rowsId; 
      
    INSERT INTO edw.sust_main_indicators_of_institutions
    VALUES
      (
        areaNo,
        dataDate,
        TABLE_NATURE,
        orgNo,
        ADD_DATE,
        rowsId,
        BATCH_DATE,
        SHEET_ID,
        OCCURRENCE_ORG,
        BWBDEPOSIT,
        RMBDEPOSIT,
        SAVINGSDEPOSIT,
        BWBLOAN,
        RMBLOAN,
        SHORTTERMLOAN,
        MEDIUMLONGTERMLOAN,
        PERSONALMLTERMLOAN
      );
  END LOOP;
  CLOSE cur;
  COMMIT;
END;
/

DROP PROCEDURE IF EXISTS edw.P_TRS_BUDGET_INCOME_COMPARE_NEW;

CREATE PROCEDURE edw.P_TRS_BUDGET_INCOME_COMPARE_NEW(IN P_DATA_DATE VARCHAR(10))
AS
  V_PROC_NAME     VARCHAR(80) := 'EDW.P_TRS_BUDGET_INCOME_COMPARE_NEW.PRC';
  V_START_TIME    CHAR(19) := NOW();
  V_STEP_ID       INT := 0;
  S_DATA_DATE     VARCHAR(8) := DATE_FORMAT(P_DATA_DATE,'%Y-%m');
  done INT := 0;
  V_DATA_DATE     VARCHAR(8);
  CURSOR cur IS   SELECT DISTINCT data_date FROM stg.trs_tmis_budget_income_provinces WHERE data_date = DATE_FORMAT(P_DATA_DATE,'%Y%m') ORDER BY data_date;
    v_at_rank VARCHAR(2000);
    v_at_rank2 VARCHAR(2000);
    v_at_tate VARCHAR(2000);
    v_at_V_ERROR_MSG VARCHAR(2000);
    v_at_V_RETURN_CODE VARCHAR(2000);
BEGIN
  
    -- NOT FOUND handler replaced by explicit cursor %NOTFOUND checks below.
 
  
  
  OPEN cur;
  LOOP
    FETCH cur INTO V_DATA_DATE;
    EXIT WHEN cur%NOTFOUND;
    IF done <> 1
    THEN 

    V_STEP_ID := 1;

    
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = V_DATA_DATE;
V_STEP_ID := 2;
INSERT INTO EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM("101_TATE"),4)
	,SUM("101_RANK")
	,ROWS_ID
FROM 
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	ROW_NUMBER() OVER (ORDER BY AA.T010101_RATE DESC) AS T010101_RANK,
	AA."101_TATE",
	AA."101_RANK",
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS "101_TATE",
	'' AS "101_RANK",
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA 
UNION ALL
(
SELECT 
	AA.DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA."101_TATE",
	ROW_NUMBER() OVER (ORDER BY AA."101_TATE" DESC)  AS "101_RANK",
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS "101_TATE",
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE

WHERE A.DATA_DATE = V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY "101_TATE" DESC
) AA 
) 
)A
GROUP BY 
        PROJECT;
        
 V_STEP_ID := 3;       
DELETE FROM EDW.TRS_BUDGET_INCOME_COMPARE WHERE DATA_DATE = CONCAT(YEAR(CONCAT(V_DATA_DATE,'01')),'Q',QUARTER(CONCAT(V_DATA_DATE,'01')));
 V_STEP_ID := 4;
INSERT INTO EDW.TRS_BUDGET_INCOME_COMPARE
SELECT 
	 DATA_DATE
	,PROJECT
	,ROUND (SUM(T010101_RATE),4)
	,SUM(T010101_RANK)
	,ROUND (SUM("101_TATE"),4)
	,SUM("101_RANK")
	,ROWS_ID
FROM 
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	ROW_NUMBER() OVER (ORDER BY AA.T010101_RATE DESC) AS T010101_RANK,
	AA."101_TATE",
	AA."101_RANK",
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS T010101_RATE,
	'' AS "101_TATE",
	'' AS "101_RANK",
        A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE
WHERE a.data_Date = V_DATA_DATE
AND a.SUBJECT_CODE = 'T010101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY T010101_RATE  DESC
) AA 
UNION ALL
(
SELECT 
	CONCAT(YEAR(CONCAT(AA.data_Date,'01')),'Q',QUARTER(CONCAT(AA.data_Date,'01'))) AS DATA_DATE,
	AA.PROJECT,
	AA.T010101_RATE,
	AA.T010101_RANK,
	AA."101_TATE",
	ROW_NUMBER() OVER (ORDER BY AA."101_TATE" DESC)  AS "101_RANK",
	AA.ROWS_ID
FROM 
(
SELECT 
	a.DATA_DATE,
	CASE WHEN a.TREDSCR = '大连市' THEN '辽宁'
             WHEN a.TREDSCR = '青岛市' THEN '山东省' 
	     WHEN a.TREDSCR = '深圳市' THEN '广东省'
             WHEN a.TREDSCR = '宁波市' THEN '浙江省'
             WHEN a.TREDSCR = '厦门市' THEN '福建省'
             WHEN a.TREDSCR = '新疆兵团' THEN '新疆区'
	     ELSE a.TREDSCR
	     END  AS PROJECT,
	'' AS T010101_RATE,
	'' AS T010101_RANK,
	(SUM(a.YEAR_AMT)-SUM(b.YEAR_AMT))/SUM(b.YEAR_AMT) AS "101_TATE",
	A.ROWS_ID
FROM stg.trs_tmis_budget_income_provinces a
LEFT JOIN stg.trs_tmis_budget_income_provinces b
       ON b.data_Date = DATE_FORMAT(DATE_SUB(CONCAT(a.data_Date,'01'),INTERVAL 1 YEAR),'%Y%m')
       AND a.TRECODE = b.TRECODE
       AND a.SUBJECT_CODE = b.SUBJECT_CODE

WHERE a.data_Date =V_DATA_DATE
AND a.SUBJECT_CODE = '101'
GROUP BY
        CASE WHEN a.TRECODE = '3501000000' THEN '0600000000'
             WHEN a.TRECODE = '3302000000' THEN '1500000000' 
	     WHEN a.TRECODE = '3801000000' THEN '1900000000'
             WHEN a.TRECODE = '3600000000' THEN '1100000000'
             WHEN a.TRECODE = '4000000000' THEN '1300000000'
	     ELSE a.TRECODE
	     END
ORDER BY "101_TATE" DESC
) AA 
) 
)A
GROUP BY 
        PROJECT;
    END IF;
  END LOOP;
  CLOSE cur;
EXCEPTION
    WHEN OTHERS THEN
       GET DIAGNOSTICS CONDITION 1 v_at_V_RETURN_CODE = RETURNED_SQLSTATE ,v_at_V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(S_DATA_DATE,V_START_TIME,NOW(),V_PROC_NAME,V_STEP_ID,v_at_V_RETURN_CODE,v_at_V_ERROR_MSG);
	END;
/

DROP PROCEDURE IF EXISTS report.p_trs_income_payout_statistics;

CREATE PROCEDURE report.p_trs_income_payout_statistics(IN V_DATA_DATE VARCHAR(20))
AS
	P_DATA_DATE  VARCHAR(20) := DATE_FORMAT(v_data_date,'%Y-%m');
	P_START_TIME CHAR(19) := NOW();
	P_PROC_NAME  VARCHAR(50) := 'report.p_trs_income_statistics.proc';
	P_STEP_ID    INT(2);
    v_at_p VARCHAR(2000);
    v_at_RANK VARCHAR(2000);
    v_at_V_ERROR_MSG VARCHAR(2000);
    v_at_V_RETURN_CODE VARCHAR(2000);
BEGIN
	
P_STEP_ID := 1;
DELETE FROM REPORT.TRS_INCOME_PAYOUT_STATISTICS_INDEX WHERE ACCOUNT_PERIOD = DATE_FORMAT(V_DATA_DATE,'%Y-%m');
P_STEP_ID := 2;
INSERT INTO REPORT.TRS_INCOME_PAYOUT_STATISTICS_INDEX
(
  ACCOUNT_PERIOD
  ,INDEX_DIM_CODE
  ,INDEX_DIM_DESCR
  ,DIMENSION_FLAG
  ,PERIOD_FLAG
  ,SUBJECT_CODE
  ,SUBJECT_DSCR
  ,INDEX_VALUE
  ,AMOUNT_RATIO
  ,ADD_USERID
  ,ADD_DATE
  ,MODIFY_USERID
  ,MODIFY_DATE
  ,TYPE
)
SELECT 
 D_ACCT,
 INDEX_DIM_CODE,
 INDEX_DIM_DESCR,
 DIMENSION_FLAG,
 PERIOD_FLAG,
 SUBJECT_CODE,
 SUBJECT_DSCR,
 INDEX_VALUE,
 AMOUNT_RATIO,
 '',
 '',
 NOW(),
 '',
 '1'
FROM
(
SELECT
  a.*,
  ROW_NUMBER() OVER (PARTITION BY a.INDEX_DIM_CODE ORDER BY a.AMOUNT_RATIO DESC) AS RANK	
FROM
(
SELECT 
    a3.D_ACCT  				AS D_ACCT,
    a3.INDEX_DIM_CODE			AS INDEX_DIM_CODE,
    a3.INDEX_DIM_DESCR 			AS INDEX_DIM_DESCR,
    a3.INDEX_VALUE 			AS INDEX_VALUE ,
    a3.INDEX_VALUE/a2.INDEX_VALUE  AS AMOUNT_RATIO,
    a3.SUBJECT_CODE 			AS SUBJECT_CODE,
    a3.SUBJECT_DSCR		AS SUBJECT_DSCR	,
    a3.	DIMENSION_FLAG  	AS DIMENSION_FLAG,
    a3. PERIOD_FLAG		AS PERIOD_FLAG
FROM 
(
SELECT  DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.PID 				  AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR,
	'1'				  AS DIMENSION_FLAG,
	'2'				  AS PERIOD_FLAG
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '101__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,
	a1.PID 
     UNION ALL 
   
      SELECT  DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID 			  AS INDEX_DIM_CODE,
	a1.AREA_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR,
	'2'				  AS DIMENSION_FLAG,
	'2'				  AS PERIOD_FLAG
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	P.AREA_NO_ID AS AREA_NO_ID, 
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '101__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a1.AREA_NO_ID ,
	a0.SUBJECT_CODE	
	) a3	
		
	LEFT JOIN(
	
		SELECT DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.PID AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4) AS INDEX_VALUE,
	a0.SUBJECT_CODE,
	a0.SUBJECT_DSCR,
	'1',
	'2'
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE=a1.CID
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m')=DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE = '101'
        AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,   
	a1.PID 
     UNION ALL
     
      SELECT DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID AS INDEX_DIM_CODE,
	a1.AREA_DSCR AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4) AS INDEX_VALUE,
	a0.SUBJECT_CODE,
	a0.SUBJECT_DSCR,
	'2',
	'2'
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.AREA_NO_ID AS AREA_NO_ID,
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE=a1.CID
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m')=DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE = '101'
        AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
     DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
     a1.AREA_NO_ID,
     a0.SUBJECT_CODE    
	) a2
        ON a3.D_ACCT = a2.D_ACCT
        AND a3.INDEX_DIM_CODE = a2.INDEX_DIM_CODE                        
        WHERE 
        a3.D_ACCT  = DATE_FORMAT(V_DATA_DATE,'%Y-%m')
        GROUP BY a3.INDEX_DIM_CODE,a3.SUBJECT_CODE
        ORDER BY a3.INDEX_DIM_CODE,a3.INDEX_VALUE/a2.INDEX_VALUE DESC 
     )   a

  )a 
  WHERE a.rank <= 8;
  
  P_STEP_ID := 3;
  
INSERT INTO REPORT.TRS_INCOME_PAYOUT_STATISTICS_INDEX
(
  ACCOUNT_PERIOD
  ,INDEX_DIM_CODE
  ,INDEX_DIM_DESCR
  ,DIMENSION_FLAG
  ,PERIOD_FLAG
  ,SUBJECT_CODE
  ,SUBJECT_DSCR
  ,INDEX_VALUE
  ,AMOUNT_RATIO
  ,ADD_USERID
  ,ADD_DATE
  ,MODIFY_USERID
  ,MODIFY_DATE
  ,TYPE
)
SELECT 
 D_ACCT,
 INDEX_DIM_CODE,
 INDEX_DIM_DESCR,
 DIMENSION_FLAG,
 PERIOD_FLAG,
 SUBJECT_CODE,
 SUBJECT_DSCR,
 INDEX_VALUE,
 AMOUNT_RATIO,
 '',
 '',
 NOW(),
 '',
 '2'
FROM
(
SELECT
  a.*,
  ROW_NUMBER() OVER (PARTITION BY a.INDEX_DIM_CODE ORDER BY a.AMOUNT_RATIO DESC) AS RANK	
FROM
(
SELECT 
    a3.D_ACCT  				AS D_ACCT,
    a3.INDEX_DIM_CODE			AS INDEX_DIM_CODE,
    a3.INDEX_DIM_DESCR 			AS INDEX_DIM_DESCR,
    a3.INDEX_VALUE 			AS INDEX_VALUE ,
    a3.INDEX_VALUE/a2.INDEX_VALUE  AS AMOUNT_RATIO,
    a3.SUBJECT_CODE 			AS SUBJECT_CODE,
    a3.SUBJECT_DSCR		AS SUBJECT_DSCR	,
    a3.	DIMENSION_FLAG  	AS DIMENSION_FLAG,
    a3. PERIOD_FLAG		AS PERIOD_FLAG
FROM 
(
SELECT  DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.PID 				  AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR,
	'1'				  AS DIMENSION_FLAG,
	'2'				  AS PERIOD_FLAG
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '2__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,
	a1.PID 
     UNION ALL 
   
      SELECT  DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID 			  AS INDEX_DIM_CODE,
	a1.AREA_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR,
	'2'				  AS DIMENSION_FLAG,
	'2'				  AS PERIOD_FLAG
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	P.AREA_NO_ID AS AREA_NO_ID, 
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '2__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a1.AREA_NO_ID ,
	a0.SUBJECT_CODE	
	) a3	
		
	LEFT JOIN(
	
		SELECT DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.PID AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4) AS INDEX_VALUE,
	a0.SUBJECT_CODE,
	a0.SUBJECT_DSCR,
	'1',
	'2'
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE=a1.CID
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m')=DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE = 'T02'
        AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,   
	a1.PID 
     UNION ALL
     
      SELECT DATE_FORMAT(V_DATA_DATE,'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID AS INDEX_DIM_CODE,
	a1.AREA_DSCR AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4) AS INDEX_VALUE,
	a0.SUBJECT_CODE,
	a0.SUBJECT_DSCR,
	'2',
	'2'
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.AREA_NO_ID AS AREA_NO_ID,
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE=a1.CID
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m')=DATE_FORMAT(V_DATA_DATE,'%Y-%m') 
        AND a0.SUBJECT_CODE = 'T02'
        AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
     DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
     a1.AREA_NO_ID,
     a0.SUBJECT_CODE    
	) a2
        ON a3.D_ACCT = a2.D_ACCT
        AND a3.INDEX_DIM_CODE = a2.INDEX_DIM_CODE                        
        WHERE 
        a3.D_ACCT  = DATE_FORMAT(V_DATA_DATE,'%Y-%m')
        GROUP BY a3.INDEX_DIM_CODE,a3.SUBJECT_CODE
        ORDER BY a3.INDEX_DIM_CODE,a3.INDEX_VALUE/a2.INDEX_VALUE DESC 
     )   a

  )a 
  WHERE a.rank <= 8;
  
P_STEP_ID := 4;
DELETE FROM REPORT.TRS_INCOME_PAYOUT_STATISTICS WHERE ACCOUNT_PERIOD = DATE_FORMAT(V_DATA_DATE,'%Y-%m');
P_STEP_ID := 5;
INSERT INTO REPORT.TRS_INCOME_PAYOUT_STATISTICS(
		 ACCOUNT_PERIOD
		,INDEX_DIM_CODE		
		,INDEX_DIM_DESCR
		,DIMENSION_FLAG
		,PERIOD_FLAG
		,SUBJECT_CODE
		,SUBJECT_DSCR
		,INDEX_VALUE
		,VALUE_YEAR
		,AMOUNT_RATIO
		,ADD_USERID
		,ADD_DATE
		,MODIFY_USERID
		,MODIFY_DATE
		,TYPE
	)
	
 SELECT 
	sta1.ACCOUNT_PERIOD AS ACCOUNT_PERIOD,
	sta1.INDEX_DIM_CODE AS INDEX_DIM_CODE,
	sta1.INDEX_DIM_DESCR AS INDEX_DIM_DESCR,
	sta1.DIMENSION_FLAG AS DIMENSION_FLAG,
	sta1.PERIOD_FLAG AS PERIOD_FLAG,
	sta1.SUBJECT_CODE AS SUBJECT_CODE,
	sta1.SUBJECT_DSCR AS SUBJECT_DSCR,
	sta1.INDEX_VALUE AS INDEX_VALUE,
	((sta1.INDEX_VALUE - sta2.INDEX_VALUE)/sta2.INDEX_VALUE) AS VALUE_YEAR,
	sta1.AMOUNT_RATIO AS AMOUNT_RATIO,
	'',
	NOW(),
	'',
	'',
	STA1.TYPE
 FROM report.trs_income_payout_statistics_index sta1
LEFT JOIN 
(
    SELECT  
        DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') AS D_ACCT,
	a1.PID 				  AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '101__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,
	a1.PID 
     UNION ALL 
   
      SELECT  DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID 			  AS INDEX_DIM_CODE,
	a1.AREA_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR
    FROM STG.trs_tmis_budget_income a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	P.AREA_NO_ID AS AREA_NO_ID, 
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '101__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a1.AREA_NO_ID ,
	a0.SUBJECT_CODE	
UNION ALL
SELECT  DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') AS D_ACCT,
	a1.PID 				  AS INDEX_DIM_CODE,
	a1.GUOKU_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	p.LEVEL,
	p.GUOKU_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '2__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a0.SUBJECT_CODE,
	a1.PID 
     UNION ALL 
   
      SELECT  DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') AS D_ACCT,
	a1.AREA_NO_ID 			  AS INDEX_DIM_CODE,
	a1.AREA_DSCR			  AS INDEX_DIM_DESCR,
	ROUND(SUM(a0.THIS_AMT),4)         AS INDEX_VALUE,
	a0.SUBJECT_CODE  		  AS SUBJECT_CODE,
	a0.SUBJECT_DSCR			  AS SUBJECT_DSCR
    FROM STG.trs_tmis_budget_payout a0
	LEFT JOIN (
	SELECT 
	DISTINCT 
	p.GUOKU_ID AS PID,
	P.AREA_NO_ID AS AREA_NO_ID, 
	p.LEVEL,
	p.GUOKU_DSCR,
	p.AREA_DSCR,
	c.GUOKU_ID AS CID
	FROM edw.cm_guoku_dimnsn p
	JOIN edw.cm_guoku_dimnsn c
	ON p.GUOKU_LVL_ID_2 = c.GUOKU_LVL_ID_1
	OR  p.GUOKU_LVL_ID_3 = c.GUOKU_LVL_ID_2 
	OR  p.GUOKU_ID = c.GUOKU_LVL_ID_3) a1 
	ON a0.TRECODE = a1.CID
    LEFT JOIN edw.cm_guoku_rcpt_dsb rc
        ON a0.SUBJECT_CODE = rc.SUBJECT_CODE_4
    WHERE DATE_FORMAT(a0.D_ACCT,'%Y-%m') = DATE_FORMAT(DATE_SUB(V_DATA_DATE,INTERVAL 1 YEAR),'%Y-%m') 
        AND a0.SUBJECT_CODE LIKE '2__'
	AND a0.LEVEL >= a1.LEVEL
	AND a0.TRECODE NOT IN('2231000000','2232000000','2233000000','2230000000') 
     GROUP BY 
	DATE_FORMAT(a0.D_ACCT,'%Y-%m'),
	a1.AREA_NO_ID ,
	a0.SUBJECT_CODE	
)  sta2
	ON  sta1.INDEX_DIM_CODE=sta2.INDEX_DIM_CODE
	AND STA1.SUBJECT_CODE = STA2.SUBJECT_CODE
WHERE sta1.ACCOUNT_PERIOD = DATE_FORMAT(V_DATA_DATE,'%Y-%m');
   
EXCEPTION
    WHEN OTHERS THEN
		GET DIAGNOSTICS CONDITION 1 v_at_V_RETURN_CODE = RETURNED_SQLSTATE ,v_at_V_ERROR_MSG = MESSAGE_TEXT;
		CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,p_START_TIME,NOW(),P_PROC_NAME,p_STEP_ID,v_at_V_RETURN_CODE,v_at_V_ERROR_MSG);
	END;
/

DROP PROCEDURE IF EXISTS edw.P_TRS_FINANCE_TAX_STATIS_NEW;

CREATE PROCEDURE edw.P_TRS_FINANCE_TAX_STATIS_NEW(IN V_DATA_DATE VARCHAR(10))
AS
v_proc_name VARCHAR(50) := 'EDW.P_TRS_FINANCE_TAX_STATIS_NEW';
V_STEP_ID   INT := '0';
P_DATA_DATE VARCHAR(50) := DATE_FORMAT(V_DATA_DATE,'%Y-%m');
V_START_TIME VARCHAR(50) := NOW();
    v_at_V_ERROR_MSG VARCHAR(2000);
    v_at_V_RETURN_CODE VARCHAR(2000);
BEGIN
V_STEP_ID := 1;
DELETE FROM EDW.TRS_FINANCE_TAX_STATIS WHERE    D_ACCT = CONCAT(
      YEAR(V_DATA_DATE),
      'Q',
      QUARTER(V_DATA_DATE)
    )
;
V_STEP_ID := 2;
INSERT INTO EDW.TRS_FINANCE_TAX_STATIS
SELECT
CONCAT(
      YEAR(CONCAT(AA.DATA_DATE,'01')),
      'Q',
      QUARTER(CONCAT(AA.DATA_DATE,'01'))
    ) AS D_ACCT     
	,AA.T_AREA_NO   
	,AA.T_AREA_DSCR 
	,AA.SERVICE_TYPE
	,AA.ROWS_ID
	,AA.UP_YEAR     
	,(AA.UP_YEAR/BB.UP_YEAR)     AS UP_YEAR_PP  
	,AA.DOWN_YEAR   
	,(AA.DOWN_YEAR/BB.DOWN_YEAR) AS DOWN_YEAR_PP
	,AA.DOWN_YEAR_Y 
FROM
(
SELECT 
	 A.DATA_DATE      
	,A.AREA_NO         AS T_AREA_NO   
	,C.AREA_DSCR       AS T_AREA_DSCR 
	,A.SERVICE_TYPE
	,A.ROWS_ID
	,SUM(A.UP_YEAR)    AS UP_YEAR     
	,SUM(A.DOWN_YEAR)  AS DOWN_YEAR   
	,(SUM(A.DOWN_YEAR)-SUM(B.DOWN_YEAR))/SUM(B.DOWN_YEAR) 		   AS DOWN_YEAR_Y  
FROM ODS.CQ_FINANCE_TAX_STATIS A 
LEFT JOIN ODS.CQ_FINANCE_TAX_STATIS B 
       ON B.DATA_DATE = DATE_FORMAT(DATE_SUB(DATE_FORMAT(CONCAT(A.DATA_DATE,'01'),'%Y%m%d'),INTERVAL 1 YEAR) ,'%Y%m')
       AND A.AREA_NO = B.AREA_NO 
       AND A.ORG_NO = B.ORG_NO 
       AND A.SERVICE_TYPE = B.SERVICE_TYPE 
LEFT JOIN DMCODE.T_AREA_CODE C 
       ON A.AREA_NO = C.AREA_NO_ID 
WHERE A.DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y%m') 
GROUP BY 
	A.DATA_DATE,  
	A.AREA_NO, 
	A.SERVICE_TYPE,
	A.ROWS_ID
) AA 
LEFT JOIN 
( 
SELECT  
	DATA_DATE, 
	AREA_NO, 
	SUM(UP_YEAR)	AS UP_YEAR, 
	SUM(DOWN_YEAR)  AS DOWN_YEAR
FROM ODS.CQ_FINANCE_TAX_STATIS 
WHERE DATA_DATE = DATE_FORMAT(V_DATA_DATE,'%Y%m') 
  AND SERVICE_TYPE = '金融业合计' 
GROUP BY 
	DATA_DATE, 
	AREA_NO, 
	SERVICE_TYPE 
) BB  
      ON AA.T_AREA_NO = BB.AREA_NO ;
EXCEPTION
    WHEN OTHERS THEN
       GET DIAGNOSTICS CONDITION 1 v_at_V_RETURN_CODE = RETURNED_SQLSTATE ,v_at_V_ERROR_MSG = MESSAGE_TEXT;
       CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),v_proc_name,V_STEP_ID,v_at_V_RETURN_CODE,v_at_V_ERROR_MSG);
	END;
/

DROP PROCEDURE IF EXISTS indicators_lib.p_xunhuan_formula_new;

CREATE PROCEDURE indicators_lib.p_xunhuan_formula_new(IN V_BATCH_DATE VARCHAR(10))
AS
	V_PROC_NAME     VARCHAR(80) := 'EDW.p_xunhuan_formula_new.PRC';
	V_START_TIME    CHAR(19) := NOW();
	V_STEP_ID       INT := 0;
	P_DATA_DATE     VARCHAR(8) := DATE_FORMAT(CONCAT(V_BATCH_DATE,'01'),'%Y-%m');
	DONE             INT := FALSE;	
	V_DATA_DATE      VARCHAR(10);          
	CURSOR CUR_D_ACCT IS 		SELECT 
	DISTINCT 
	 
	DATE_FORMAT(CONCAT(REPLACE(d_acct,'-',''),''),'%Y-%m-%d')
	  AS d_acct
	FROM 
	(
	
	SELECT D_ACCT 
	FROM STG.TRS_TMIS_STOCK
	WHERE (data_date LIKE    CONCAT(V_BATCH_DATE,'%')
	OR data_date LIKE  CONCAT(DATE_FORMAT(CONCAT(REPLACE(DATE_FORMAT(CONCAT('202512','01'),'%Y-%m'),'-',''),'01'),'%Y%m'),'%')) )a
	

	;
	CURSOR CUR_MONTH IS 	SELECT 
	DISTINCT 
	IF(
	DATE_FORMAT(d_acct,'%Y-%m-%d') IS NULL,

	DATE_FORMAT(CONCAT(REPLACE(d_acct,'-',''),'01'),'%Y-%m'),
	DATE_FORMAT(d_acct,'%Y-%m')
	) AS d_acct
	FROM 
	(
	SELECT D_ACCT 
	FROM STG.TRS_TMIS_BUDGET_INCOME
	WHERE DATA_DATE = CONCAT(V_BATCH_DATE)
	UNION ALL 
	SELECT D_ACCT 
	FROM STG.TRS_TMIS_BUDGET_PAYOUT
	WHERE DATA_DATE = CONCAT(V_BATCH_DATE)
	  )a
	ORDER BY
	IF(
	DATE_FORMAT(d_acct,'%Y-%m-%d') IS NULL,

DATE_FORMAT(CONCAT(REPLACE(d_acct,'-',''),'01'),'%Y-%m'),
	DATE_FORMAT(d_acct,'%Y-%m-%d')
	);
    v_at_V_ERROR_MSG VARCHAR(2000);
    v_at_V_RETURN_CODE VARCHAR(2000);
BEGIN
	
	
	
    -- NOT FOUND handler replaced by explicit cursor %NOTFOUND checks below.
	
	
	
	 V_STEP_ID := 1;

	
	UPDATE STG.TRS_TMIS_BUDGET_INCOME 
	SET D_ACCT = CASE WHEN LENGTH(D_ACCT) = 6 
				THEN DATE_FORMAT(CONCAT(D_ACCT,'01'),'%Y-%m-%d') 
				ELSE DATE_FORMAT(D_ACCT,'%Y-%m-%d') END;
	CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),'gk',V_STEP_ID,v_at_V_RETURN_CODE,'222');
	 V_STEP_ID := 2;
	UPDATE STG.TRS_TMIS_BUDGET_PAYOUT 
	SET D_ACCT = CASE WHEN LENGTH(D_ACCT) = 6 
				THEN DATE_FORMAT(CONCAT(D_ACCT,'01'),'%Y-%m-%d') 
				ELSE DATE_FORMAT(D_ACCT,'%Y-%m-%d') END;
			CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),'gk',V_STEP_ID,v_at_V_RETURN_CODE,'33');

	 V_STEP_ID := 3;
	UPDATE STG.TRS_TMIS_STOCK SET TRECODE = '2200000000' ,TREDSCR = '国家金库重庆市分库' WHERE TRECODE = 'NNNNNNNNNN';

	
	 V_STEP_ID := 4;
	CALL edw.P_TRS_BUDGET_INCOME_COMPARE_NEW(DATE_FORMAT(CONCAT(V_BATCH_DATE,'01'),'%Y%m%d'));

	V_STEP_ID := 5;
	    CALL report.p_trs_income_payout_statistics(DATE_FORMAT(CONCAT(V_BATCH_DATE,'01'),'%Y%m%d'));

	    V_STEP_ID := 6;
	    CALL edw.P_TRS_FINANCE_TAX_STATIS_NEW(DATE_FORMAT(CONCAT(V_BATCH_DATE,'01'),'%Y%m%d'));

	 
	  
	
	OPEN CUR_D_ACCT;
	<<ENTLOOP>>
	LOOP
		FETCH CUR_D_ACCT INTO V_DATA_DATE;
		EXIT WHEN CUR_D_ACCT%NOTFOUND;
		IF DONE THEN
		EXIT ENTLOOP;
		END IF;

		 V_STEP_ID := 7;
		
	 	 CALL indicators_lib.p_exe_formula_hand(V_DATA_DATE,'e34ac06898ce11eab404000c298a21af'); 
	 	 CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),'gk',V_STEP_ID,v_at_V_RETURN_CODE,'777');
		
		
	        
	         V_STEP_ID := 8;
	        IF V_DATA_DATE = CONCAT(DATE_FORMAT(V_DATA_DATE,'%Y-%m'),'-01')

	        THEN
	        CALL indicators_lib.p_exe_formula(V_DATA_DATE); 
	    
	        CALL report.P_QUARTER_REPORT_TEXT(CONCAT(YEAR(V_DATA_DATE),'Q',QUARTER(V_DATA_DATE)));
	        CALL report.P_NEWS_FLASH_QUARTER_REPORT_TEXT(CONCAT(YEAR(V_DATA_DATE),'Q',QUARTER(V_DATA_DATE)));
	        
	        END IF;	
	
		END LOOP ENTLOOP;
		CLOSE CUR_D_ACCT;
		DONE := FALSE;
	
	OPEN CUR_MONTH;
	<<MONTHLOOP>>
	LOOP
		FETCH CUR_MONTH INTO V_DATA_DATE;
		EXIT WHEN CUR_MONTH%NOTFOUND;
		IF DONE THEN
		EXIT MONTHLOOP;
		END IF;
		
	 	 V_STEP_ID := 9;
		CALL report.P_MONTH_REPORT_TEXT(V_DATA_DATE);
	        CALL report.P_NEWS_FLASH_MONTH_REPORT_TEXT(V_DATA_DATE);
	        CALL report.P_NEWS_FLASH_MONTH_TEXT_NUMBER(CONCAT(V_DATA_DATE,'-01'));
	        CALL visual_screen.P_task_vscreen_new(V_BATCH_DATE);
	         CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),'gk',V_STEP_ID,v_at_V_RETURN_CODE,'999');
	        
		END LOOP MONTHLOOP;
		CLOSE CUR_MONTH;
		DONE := FALSE;
	
EXCEPTION
    WHEN OTHERS THEN
	GET DIAGNOSTICS CONDITION 1 v_at_V_RETURN_CODE = RETURNED_SQLSTATE ,v_at_V_ERROR_MSG = MESSAGE_TEXT;
	CALL ETL.EDW_PROC_ERROR_LOG(P_DATA_DATE,V_START_TIME,NOW(),'gk',V_STEP_ID,v_at_V_RETURN_CODE,v_at_V_ERROR_MSG);
	END;
/

