#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <schema> <input.sql> <output.sql>" >&2
  exit 1
fi

schema="$1"
input="$2"
output="$3"

awk -v schema="$schema" '
BEGIN {
  print "-- Generated by normalize_vastbase_mysql_bundle.sh"
  print "SET search_path TO " schema ", public;"
  print ""
}
{
  line = $0

  if (line ~ /^DELIMITER[[:space:]]+\$\$$/ || line ~ /^DELIMITER[[:space:]]+;$/) {
    next
  }

  if (line ~ /^\$\$$/) {
    print ";"
    next
  }

  if (line ~ /^CREATE DEFINER=/) {
    sub(/^CREATE DEFINER=`[^`]+`@`[^`]+` PROCEDURE[[:space:]]+/, "CREATE PROCEDURE ", line)
    gsub(/`/, "", line)
    prefix = "^CREATE PROCEDURE " schema "\\."
    if (line !~ prefix) {
      sub(/^CREATE PROCEDURE[[:space:]]+/, "CREATE PROCEDURE " schema ".", line)
    }
    print line
    next
  }

  if (line ~ /^DROP PROCEDURE IF EXISTS /) {
    gsub(/`/, "", line)
    print line
    next
  }

  if (line ~ /^[[:space:]]*DECLARE EXIT HANDLER FOR SQLEXCEPTION/) {
    print "    DECLARE V_RETURN_CODE TEXT;"
    print "    DECLARE V_ERROR_MSG TEXT;"
  }

  gsub(/`/, "", line)
  gsub(/@V_RETURN_CODE/, "V_RETURN_CODE", line)
  gsub(/@V_ERROR_MSG/, "V_ERROR_MSG", line)
  print line
}
' "$input" > "$output"
