-- Raw MySQL event DDL export
-- Generated by MySqlDdlDump

-- EVENT `indicators_lib`.`p_init_report01`
DROP EVENT IF EXISTS `indicators_lib`.`p_init_report01`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `p_init_report01` ON SCHEDULE EVERY 1 DAY STARTS '2023-09-05 21:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL indicators_lib.init_report01 (DATE_FORMAT(LAST_DAY(date_add(CURDATE(),interval -1 MONTH)), '%Y-%m-%d'))
$$
DELIMITER ;

-- EVENT `indicators_lib`.`p_init_report02`
DROP EVENT IF EXISTS `indicators_lib`.`p_init_report02`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `p_init_report02` ON SCHEDULE EVERY 1 DAY STARTS '2023-09-05 23:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL indicators_lib.init_report02 (DATE_FORMAT(LAST_DAY(date_add(CURDATE(),interval -1 MONTH)), '%Y-%m-%d'))
$$
DELIMITER ;

-- EVENT `indicators_lib`.`p_init_report03`
DROP EVENT IF EXISTS `indicators_lib`.`p_init_report03`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `p_init_report03` ON SCHEDULE EVERY 1 DAY STARTS '2023-09-06 02:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL indicators_lib.init_report03 (DATE_FORMAT(LAST_DAY(date_add(CURDATE(),interval -1 MONTH)), '%Y-%m-%d'))
$$
DELIMITER ;

-- EVENT `indicators_lib`.`p_xunhuan_formula`
DROP EVENT IF EXISTS `indicators_lib`.`p_xunhuan_formula`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `p_xunhuan_formula` ON SCHEDULE EVERY 1 DAY STARTS '2021-04-25 18:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL indicators_lib.p_xunhuan_formula (DATE_FORMAT(CURDATE(), '%Y%m%d'))
$$
DELIMITER ;

-- EVENT `ods`.`pt_gy_files_task`
DROP EVENT IF EXISTS `ods`.`pt_gy_files_task`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `pt_gy_files_task` ON SCHEDULE EVERY 1 DAY STARTS '2021-02-25 01:00:00' ON COMPLETION NOT PRESERVE ENABLE DO call ods.p_pt_gy_files_temp()
$$
DELIMITER ;

-- EVENT `seo`.`P_task_vs`
DROP EVENT IF EXISTS `seo`.`P_task_vs`;
DELIMITER $$
CREATE DEFINER=`dis`@`%` EVENT `P_task_vs` ON SCHEDULE EVERY 1 DAY STARTS '2021-01-06 02:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL visual_screen.P_task_vscreen (DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY),'%Y%m%d'))
$$
DELIMITER ;

-- EVENT `visual_screen`.`P_task_vs`
DROP EVENT IF EXISTS `visual_screen`.`P_task_vs`;
DELIMITER $$
CREATE DEFINER=`root`@`%` EVENT `P_task_vs` ON SCHEDULE EVERY 1 DAY STARTS '2021-04-25 18:15:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL visual_screen.P_task_vscreen (
    DATE_FORMAT(CURDATE(),'%Y%m%d'))
$$
DELIMITER ;

