#********* solarwinds接口访问参数 **********
SOLARWINDS_IP=11.8.2.184
SOLARWINDS_PORT=17778
SOLARWINDS_HOSTNAME=11.8.2.184
SOLARWINDS_USERNAME=bda
SOLARWINDS_PASSWORD=Password@023
#********* 优云接口访问参数 **********
UCLOUD_IP=11.8.174.9
UCLOUD_PORT=80
UCLOUD_APIKEY=e10adc3949ba59abbe56e057f2gg88dd
#********* 优云指标告警数据接口 **********
UCLOUD_ALERT=http://${UCLOUD_IP}/alert/openapi/v2/incident/query?apikey=${UCLOUD_APIKEY}&pageNo=1&pageSize=1000
#********* UPM接口访问参数 **********
UPM_IP=11.8.196.10
UPM_PORT=443
UPM_TABLE_SECRETKEY=c17c7cc9e8833e845eeda3a87a908ad2cb5f8a29
UPM_FIELDS_SECRETKEY=1d275c2d916ff2620af3db158b7c7168b6aebf26
UPM_QUERY_SECRETKEY=86789263bdc928d2b2c135e6696f32f2c6e68ba8
#********* 子进程process **********
ucloudProcess=6be0cf1f6432447f893efb7e7c1d8a7b
upmProcess=0e6a26e43ca740298a793a3dba8c4e90
solarwindsProcess=xxxxxxxxxx
#********* 子进程状态附件保存路径 **********
fileSavePath=/home/processStatus/
#********* 接口重调上限 **********
restartCount=3
#********* 接口存活生命周期，单位分钟 **********
liveTime=60
#********* 接口历史数据跑批起始日期 **********
queryDay=2020-10-01

#每天 16点30执行
cronThreeCertificates=0 30 16 * * ?
#每天 17点30执行
cronEnterprise=0 59 19 * * ?
#接口数据每页多少条
httpPage=1000
#当前页
page=1
#终止页
size=1
#10天之内
day=10
loginName=gkcadmin
loginPassword=Guokuchu4*1
#每天 17点30执行  scp 取文件定时任务   9.16.20.170
scpFileTimeOne=0 30 16 * * ?
#每天 17点30执行  scp 取文件定时任务   9.16.20.171
scpFileTimeTwo=0 30 19 * * ?