#vastbase 
diver_name=org.postgresql.Driver
url=jdbc:postgresql://100.71.11.54:25432/gk_data_analysis?currentSchema=%22jeecg-boot-os%22,public
username=vastbase_test
password=B$S8*^75foTnE*z1
database_name=gk_data_analysis