TEMPLATE_FILE_PATH=/home/app/pbc-file/
spring.datasource.default.url=jdbc:postgresql://100.71.11.54:25432/gk_data_analysis?currentSchema=seo,edw,public
spring.datasource.default.username=vastbase_test
spring.datasource.default.password=B$S8*^75foTnE*z1
spring.datasource.default.driverClassName=org.postgresql.Driver
spring.datasource.default.validationQuery=SELECT 1
spring.datasource.default.testOnBorrow=false
spring.datasource.default.testOnReturn=false
spring.datasource.default.testWhileIdle=true
spring.datasource.default.filters=stat,wall,slf4j
spring.datasource.default.maxActive=20